name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Lint frontend
        run: |
          cd frontend
          npm run lint

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Set up Go for backend
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install backend dependencies
        run: go mod download

      - name: Build backend
        run: go build -v ./cmd/main.go

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Backend Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-BACKEND_ID?key=https://api.render.com/deploy/srv-d1kvmpbe5dus73f2il0g?key=DcWBXI01Xp8Y"
      - name: Trigger Frontend Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-FRONTEND_ID?key=https://api.render.com/deploy/srv-d1l0423e5dus73f2uvs0?key=KjyeO8Xmu1oY"
